### PR TITLE
Add section on test case reduction, correct typoes

### PR DESCRIPTION
**Pull request by colin-scott**

### CODE REVIEW

**Comment by asatarin** [comment]
I'm going to need some time to read papers you linked.

Also think non-paywalled link to P# paper would be better
https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/paper-6.pdf

**Comment by colin-scott** [comment]
Any progress on the paper reading? ;-)

**Comment by asatarin** [comment]
Half done.

**Comment by colin-scott** [comment]
Thanks!

**Pull request merged**
